const track = {
  album: {
    album_type: 'album',
    artists: [
      {
        external_urls: { spotify: 'https://open.spotify.com/artist/0gxyHStUsqpMadRV0Di1Qt' },
        href: 'https://api.spotify.com/v1/artists/0gxyHStUsqpMadRV0Di1Qt',
        id: '0gxyHStUsqpMadRV0Di1Qt',
        name: 'Rick Astley',
        type: 'artist',
        uri: 'spotify:artist:0gxyHStUsqpMadRV0Di1Qt'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    external_urls: { spotify: 'https://open.spotify.com/album/6N9PS4QXF1D0OWPk0Sxtb4' },
    href: 'https://api.spotify.com/v1/albums/6N9PS4QXF1D0OWPk0Sxtb4',
    id: '6N9PS4QXF1D0OWPk0Sxtb4',
    images: [
      { height: 640, url: 'https://i.scdn.co/image/ab67616d0000b273255e131abc1410833be95673', width: 640 },
      { height: 300, url: 'https://i.scdn.co/image/ab67616d00001e02255e131abc1410833be95673', width: 300 },
      { height: 64, url: 'https://i.scdn.co/image/ab67616d00004851255e131abc1410833be95673', width: 64 }
    ],
    name: 'Whenever You Need Somebody',
    release_date: '1987-11-12',
    release_date_precision: 'day',
    total_tracks: 10,
    type: 'album',
    uri: 'spotify:album:6N9PS4QXF1D0OWPk0Sxtb4'
  },
  artists: [
    {
      external_urls: { spotify: 'https://open.spotify.com/artist/0gxyHStUsqpMadRV0Di1Qt' },
      href: 'https://api.spotify.com/v1/artists/0gxyHStUsqpMadRV0Di1Qt',
      id: '0gxyHStUsqpMadRV0Di1Qt',
      name: 'Rick Astley',
      type: 'artist',
      uri: 'spotify:artist:0gxyHStUsqpMadRV0Di1Qt'
    }
  ],
  available_markets: [
    'AD',
    'AE',
    'AL',
    'AR',
    'AT',
    'AU',
    'BA',
    'BE',
    'BG',
    'BH',
    'BO',
    'BR',
    'BY',
    'CA',
    'CH',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DE',
    'DK',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'FI',
    'FR',
    'GB',
    'GR',
    'GT',
    'HK',
    'HN',
    'HR',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IS',
    'IT',
    'JO',
    'JP',
    'KW',
    'KZ',
    'LB',
    'LI',
    'LT',
    'LU',
    'LV',
    'MA',
    'MC',
    'MD',
    'ME',
    'MK',
    'MT',
    'MX',
    'MY',
    'NI',
    'NL',
    'NO',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PH',
    'PL',
    'PS',
    'PT',
    'PY',
    'QA',
    'RO',
    'RS',
    'RU',
    'SA',
    'SE',
    'SG',
    'SI',
    'SK',
    'SV',
    'TH',
    'TN',
    'TR',
    'TW',
    'UA',
    'UY',
    'VN',
    'XK',
    'ZA'
  ],
  disc_number: 1,
  duration_ms: 213573,
  explicit: false,
  external_ids: { isrc: 'GBARL9300135' },
  external_urls: { spotify: 'https://open.spotify.com/track/4uLU6hMCjMI75M1A2tKUQC' },
  href: 'https://api.spotify.com/v1/tracks/4uLU6hMCjMI75M1A2tKUQC',
  id: '4uLU6hMCjMI75M1A2tKUQC',
  is_local: false,
  name: 'Never Gonna Give You Up',
  popularity: 77,
  preview_url:
    'https://p.scdn.co/mp3-preview/a69cabb16c6c3333db903d1f538e808493689e40?cid=f46911bd4ae145d9a85e08ea4dae3402',
  track_number: 1,
  type: 'track',
  uri: 'spotify:track:4uLU6hMCjMI75M1A2tKUQC'
};

export default track;
